name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip' # pip 캐시
      # 종속성 설치 및 requirements.txt
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
            pip --version
      # Python 버전 출력
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # 구구단을 출력하는 nbn.py 실행
      - name: Run nbn.py (Multiplication Table)
        run: python nbn.py
